@include('front.includes.headtags')
@include('front.includes.header')
@include('front.includes.footer')
@include('front.includes.endtags')

@yield('headtags')
@yield('header')
@yield('content')
@yield('footer')
@yeild('endtags')